version: 2
updates:
  # Maintain Python dependencies for vedium_core
  - package-ecosystem: "pip"
    directory: "/vedium_core"
    schedule:
      interval: "daily"
    reviewers:
      - "ivonsmatos"

  # Maintain NPM dependencies for vedium_core
  - package-ecosystem: "npm"
    directory: "/vedium_core"
    schedule:
      interval: "daily"
    reviewers:
      - "ivonsmatos"

  # Maintain GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
