global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'vedium-frappe'
    metrics_path: '/api/method/vedium_core.vedium_core.api.get_metrics'
    static_configs:
      - targets: ['vedium-frappe:8000']
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
